[package]
name = "rcon"
version = "0.1.0"
authors = ["Bruno Bigras <bigras.bruno@gmail.com>"]

[dependencies]
byteorder = "1.2"
failure = "0.1"
nom = "3.2"
r2d2 = { version = "0.8", optional = true }

[features]
default = []
with-r2d2 = ["r2d2"]